name: Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a CodeSandbox, StackBlitz, or minimum repository to reproduce the issue.
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: e.g. Node 20.x, React 18, Tailwind v4
    validations:
      required: true
